### ISSUE TITLE
Test plugin

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_auto_replace#10]
@kvichans поможете потестировать бету, плс?

**Comment by Alexey-T** [comment]
@iRamSoft 
не работает.
пример снипов
http://synwrite.sourceforge.net/forums/viewtopic.php?p=11947#p11947

я сделал для Паскаля два снип файла и положил их в data/autoreplace/Pascal.
```
writeln WriteLn
write Write
```
file2-
```
ioresult IOResult
```

плагин пишет "works for all files". печатаю в Пас файле writeln<space> - не меняет.

**Comment by iRamSoft** [comment]
А расширение файлов какое?
Не могу повторить у себя

**Comment by Alexey-T** [comment]
.cuda-snips, после ренейма папки в ниж рег СНиПы работают, а про завис я написал в др топик.

**Comment by iRamSoft** [comment]
У меня папка с верхним регистром, зависание сейчас проверю.

**Comment by Alexey-T** [comment]
У тебя регистр не важен на Вин
