### ISSUE TITLE
plugin hanged

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_auto_replace#11]
завис после набора в новой файле
```
writeln<space>
WRIteln<space>
```
![screenshot from 2018-08-28 10-36-36](https://user-images.githubusercontent.com/4154978/44708259-56610e00-aaaf-11e8-96f9-01a251a76911.png)

есть 2 файла с снипами
data/autoreplace/Pascal

```
writeln WriteLn
write Write
read Read
readln ReadLn
```
file2
```
ioresult IOResult

```

**Comment by Alexey-T** [comment]
надо было назвать dir: pascal. а то вообще не найдет снипы. но завис есть и так и так. с 'pascal' он меняет слово и завис.

Linux Ubuntu 18.x gtk2

**Comment by iRamSoft** [comment]
Ты меня заставляешь Ubuntu ставить, на Win нет зависания

**Comment by Alexey-T** [comment]
Такое может быть , из за LCL и порядка вызова евентов на осях

**Comment by iRamSoft** [comment]
B как быть?

**Comment by Alexey-T** [comment]
Проверить на лин, повторить баг

**Comment by Alexey-T** [comment]
я добавил Принт в каждый метод Комманд. 
печатаю слово "write" +пробел.
и тут же завис.
смотри как дофига всего у тебя вызвалось. =(

там еще больше не видно

![plg-hang](https://user-images.githubusercontent.com/4154978/44732327-b4ace180-aaed-11e8-9272-ed45c4374c10.png)

**Comment by Alexey-T** [comment]
вывел `on key >> [code]` для входа в on_key.
вижу баг Куды- два раза выховы на 1 клавишу
это и дает завис.

![hang2](https://user-images.githubusercontent.com/4154978/44734001-87623280-aaf1-11e8-9f2e-e24a63f365e7.png)

**Comment by iRamSoft** [comment]
Добавил костыль: https://github.com/iRamSoft/cuda_auto_replace/commit/dd0fa5b33035be0170c8c9c739a16330c4e50ba2

**Comment by Alexey-T** [comment]
problem in CudaTree.
