### ISSUE TITLE
is a comment

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_auto_replace#20]
```
def is_not_a_comment(style):
    return style.lower() not in ['string','comment']
```

не всегда сработает. Надо бы читать список стилей (для кое каких он бвает не 'string', 'comment') через lexer_proc().
и закешировать ответ lexer_proc.

**Comment by iRamSoft** [comment]
А что ещё может быть? Точнее в каком случае не сработает?

**Comment by Alexey-T** [comment]
можешь скачать все аддоны, потом в папке лексеров поискать в *.lcf - для строк бывает 'str', 'string2', 'string alt', 'regex string' -разное

**Comment by Alexey-T** [comment]
2) двойное отрицание (not  в коде, в имени ф-ции, в вызове ф-ции) -- надо без отрицания

**Comment by iRamSoft** [comment]
Готово

**Comment by Alexey-T** [comment]
если работает, то Ок, по коду- Ок.
