### ISSUE TITLE
fix for i.lower()

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_auto_replace#33]
@iRamSoft 
твой фикс с i.lower()- он на что то влияет? потому что я тестил и работало и так.

**Comment by iRamSoft** [comment]
У меня без этого не работало

**Comment by iRamSoft** [comment]
Полностью

**Comment by Alexey-T** [comment]
у меня работало- вот мой файл для паскаля -
```
writeln WriteLn
write Write
read Read
readln ReadLn
```

**Comment by Alexey-T** [comment]
только если у тебя слово-0 не в lowercase, не работает.
