### ISSUE TITLE
simpler snippet files

### ISSUE THREAD

**Issue by Alexey-T** [iRamSoft/cuda_auto_replace#34]
можно вместо файлов типа
```
writeln WriteLn
write Write
read Read
readln ReadLn

```
сдплать
```
WriteLn
Write
Read
ReadLn
```

это даст проще файлы. надо будет тогда поменять расширение файлов. 
это уже не тот формат.
стОит ли делать?
@iramsoft

**Comment by iRamSoft** [comment]
Я бы поменял, т.к. не вижу смысла в избыточной инфоомации

**Comment by Alexey-T** [comment]
Поменяешь плис?

Новое расширение у снипов пусть например .cuda-rep

**Comment by iRamSoft** [comment]
Это скорее dic (Dictionary) чём rep

**Comment by iRamSoft** [comment]
Да, поменяю

**Comment by Alexey-T** [comment]
Ок, .cuda-dic

**Comment by Alexey-T** [comment]
pull req..
